apiVersion: v2
name: popular-moviestore
description: A Helm chart for Kubernetes
type: application
version: 1.0.1
appVersion: 1.0.0
home: https://eformat.github.io/helm-charts
maintainers:
- name: eformat
