{{- if .Values.istio.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-same-namespace
  labels:
    {{- include "popular-moviestore.labels" . | nindent 4 }}
spec:
  ingress:
    - from:
        - podSelector: {}
{{- end }}
