---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "popular-moviestore.fullname" . }}
  labels:
    {{- include "popular-moviestore.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      deploymentconfig: {{ include "popular-moviestore.fullname" . }}
