apiVersion: v1
data:
  API_KEY: dW5zZXQ=
  INFINISPAN_PASSWORD: cGFzc3dvcmQ=
  INFINISPAN_REALM: ZGVmYXVsdA==
  INFINISPAN_SERVICE_HOST: aW5maW5pc3Bhbi5kYXRhZ3JpZC5zdmMuY2x1c3Rlci5sb2NhbA==
  INFINISPAN_SERVICE_PORT: MTEyMjI=
  INFINISPAN_USER: ZGV2ZWxvcGVy
kind: Secret
metadata:
  name: {{ include "popular-moviestore.fullname" . }}
  labels:
    {{- include "popular-moviestore.labels" . | nindent 4 }}
type: Opaque
