---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "popular-moviestore.fullname" . }}
  labels:
    {{- include "popular-moviestore.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: tcp-8080
    - port: 8443
      protocol: TCP
      targetPort: 8443
      name: tcp-8443
  selector:
    {{- include "popular-moviestore.selectorLabels" . | nindent 4 }}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
