package org.acme.moviestore;

import org.acme.data.Movie;
import org.acme.data.MovieCartItem;

import javax.annotation.PostConstruct;
import java.util.ArrayList;
import java.util.List;

/**
 * We load these movies if API_KEY is not set
 */
public class TestMovies {

    public List<MovieCartItem> movieList = new ArrayList<>();

    public TestMovies() {
        loadMovies();
    }

    @PostConstruct
    private void loadMovies() {
        movieList.add(new MovieCartItem(new Movie("601844", "http://image.tmdb.org/t/p/w92/xqbQtMffXwa3oprse4jiHBMBvdW.jpg", "http://image.tmdb.org/t/p/w45/qTrpw2ZUvN7ywUu1kieEsvNDrgQ.jpg", "A teenager's weekend at a lake house with her father takes a turn for the worse when a group of convicts wreaks havoc on their lives.", "Becky", 5.6f, false, null, "en", "Becky", null, false, 77)));
        movieList.add(new MovieCartItem(new Movie("539885", "http://image.tmdb.org/t/p/w92/qzA87Wf4jo1h8JMk9GilyIYvwsA.jpg", "http://image.tmdb.org/t/p/w45/54yOImQgj8i85u9hxxnaIQBRUuo.jpg", "A black ops assassin is forced to fight for her own survival after a job goes dangerously wrong.", "Ava", 5.8f, false, null, "en", "Ava", null, false, 563)));
        movieList.add(new MovieCartItem(new Movie("354912", "http://image.tmdb.org/t/p/w92/gGEsBPAijhVUFoiNpgZXqRVWJt2.jpg", "http://image.tmdb.org/t/p/w45/askg3SMvhqEl4OL52YuvdtY40Yb.jpg", "Despite his family’s baffling generations-old ban on music, Miguel dreams of becoming an accomplished musician like his idol, Ernesto de la Cruz. Desperate to prove his talent, Miguel finds himself in the stunning and colorful Land of the Dead following a mysterious chain of events. Along the way, he meets charming trickster Hector, and together, they set off on an extraordinary journey to unlock the real story behind Miguel's family history.", "Coco", 8.2f, false, null, "en", "Coco", null, false, 12617)));
        movieList.add(new MovieCartItem(new Movie("581392", "http://image.tmdb.org/t/p/w92/sy6DvAu72kjoseZEjocnm2ZZ09i.jpg", "http://image.tmdb.org/t/p/w45/2nFzxaAK7JIsk6l7qZ8rFBsa3yW.jpg", "A soldier and his team battle hordes of post-apocalyptic zombies in the wastelands of the Korean Peninsula.", "Peninsula", 7.0f, false, null, "ko", "반도", null, false, 699)));
        movieList.add(new MovieCartItem(new Movie("497582", "http://image.tmdb.org/t/p/w92/riYInlsq2kf1AWoGm80JQW5dLKp.jpg", "http://image.tmdb.org/t/p/w45/kMe4TKMDNXTKptQPAdOF0oZHq3V.jpg", "While searching for her missing mother, intrepid teen Enola Holmes uses her sleuthing skills to outsmart big brother Sherlock and help a runaway lord.", "Enola Holmes", 7.6f, false, null, "en", "Enola Holmes", null, false, 2403)));
        movieList.add(new MovieCartItem(new Movie("590223", "http://image.tmdb.org/t/p/w92/r4Lm1XKP0VsTgHX4LG4syAwYA2I.jpg", "http://image.tmdb.org/t/p/w45/lA5fOBqTOQBQ1s9lEYYPmNXoYLi.jpg", "Seven years after the Monsterpocalypse, Joel Dawson, along with the rest of humanity, has been living underground ever since giant creatures took control of the land. After reconnecting over radio with his high school girlfriend Aimee, who is now 80 miles away at a coastal colony, Joel begins to fall for her again. As Joel realizes that there’s nothing left for him underground, he decides against all logic to venture out to Aimee, despite all the dangerous monsters that stand in his way.", "Love and Monsters", 7.7f, false, null, "en", "Love and Monsters", null, false, 264)));
        movieList.add(new MovieCartItem(new Movie("740985", "http://image.tmdb.org/t/p/w92/6agKYU5IQFpuDyUYPu39w7UCRrJ.jpg", "http://image.tmdb.org/t/p/w45/hbrXbVoE0NuA1ORoSGGYNASagrl.jpg", "14 years after making a film about his journey across the USA, Borat risks life and limb when he returns to the United States with his young daughter, and reveals more about the culture, the COVID-19 pandemic, and the political elections.", "Borat Subsequent Moviefilm", 6.7f, false, null, "en", "Borat Subsequent Moviefilm", null, false, 664)));
        movieList.add(new MovieCartItem(new Movie("635302", "http://image.tmdb.org/t/p/w92/h8Rb9gBr48ODIwYUttZNYeMWeUU.jpg", "http://image.tmdb.org/t/p/w45/xoqr4dMbRJnzuhsWDF3XNHQwJ9x.jpg", "Tanjirō Kamado, joined with Inosuke Hashibira, a boy raised by boars who wears a boar's head, and Zenitsu Agatsuma, a scared boy who reveals his true power when he sleeps, boards the Infinity Train on a new mission with the Fire Hashira, Kyōjurō Rengoku, to defeat a demon who has been tormenting the people and killing the demon slayers who oppose it!", "Demon Slayer: Kimetsu no Yaiba - The Movie: Mugen Train", 6.7f, false, null, "ja", "劇場版「鬼滅の刃」無限列車編", null, false, 33)));
        movieList.add(new MovieCartItem(new Movie("337401", "http://image.tmdb.org/t/p/w92/aKx1ARwG55zZ0GpRvU2WrGrCG9o.jpg", "http://image.tmdb.org/t/p/w45/zzWGRw277MNoCs3zhyG3YmYQsXv.jpg", "When the Emperor of China issues a decree that one man per family must serve in the Imperial Chinese Army to defend the country from Huns, Hua Mulan, the eldest daughter of an honored warrior, steps in to take the place of her ailing father. She is spirited, determined and quick on her feet. Disguised as a man by the name of Hua Jun, she is tested every step of the way and must harness her innermost strength and embrace her true potential.", "Mulan", 7.2f, false, null, "en", "Mulan", null, false, 2734)));
        movieList.add(new MovieCartItem(new Movie("694919", "http://image.tmdb.org/t/p/w92/6CoRTJTmijhBLJTUNoVSUNxZMEI.jpg", "http://image.tmdb.org/t/p/w45/pq0JSpwyT2URytdFG0euztQPAyR.jpg", "A professional thief with $40 million in debt and his family's life on the line must commit one final heist - rob a futuristic airborne casino filled with the world's most dangerous criminals.", "Money Plane", 6.0f, false, null, "en", "Money Plane", null, false, 161)));
        movieList.add(new MovieCartItem(new Movie("718444", "http://image.tmdb.org/t/p/w92/uOw5JD8IlD546feZ6oxbIjvN66P.jpg", "http://image.tmdb.org/t/p/w45/x4UkhIQuHIJyeeOTdcbZ3t3gBSa.jpg", "Battle-hardened O’Hara leads a lively mercenary team of soldiers on a daring mission: rescue hostages from their captors in remote Africa. But as the mission goes awry and the team is stranded, O’Hara’s squad must face a bloody, brutal encounter with a gang of rebels.", "Rogue", 5.8f, false, null, "en", "Rogue", null, false, 337)));
        movieList.add(new MovieCartItem(new Movie("531219", "http://image.tmdb.org/t/p/w92/betExZlgK0l7CZ9CsCBVcwO1OjL.jpg", "http://image.tmdb.org/t/p/w45/8rIoyM6zYXJNjzGseT3MRusMPWl.jpg", "In late 1967, a young orphaned boy goes to live with his loving grandma in the rural Alabama town of Demopolis. As the boy and his grandmother encounter some deceptively glamorous but thoroughly diabolical witches, she wisely whisks him away to a seaside resort. Regrettably, they arrive at precisely the same time that the world's Grand High Witch has gathered.", "Roald Dahl's The Witches", 7.1f, false, null, "en", "Roald Dahl's The Witches", null, false, 472)));
        movieList.add(new MovieCartItem(new Movie("724989", "http://image.tmdb.org/t/p/w92/ugZW8ocsrfgI95pnQ7wrmKDxIe.jpg", "http://image.tmdb.org/t/p/w45/86L8wqGMDbwURPni2t7FQ0nDjsH.jpg", "The work of billionaire tech CEO Donovan Chalmers is so valuable that he hires mercenaries to protect it, and a terrorist group kidnaps his daughter just to get it.", "Hard Kill", 4.4f, false, null, "en", "Hard Kill", null, false, 62)));
        movieList.add(new MovieCartItem(new Movie("741067", "http://image.tmdb.org/t/p/w92/elZ6JCzSEvFOq4gNjNeZsnRFsvj.jpg", "http://image.tmdb.org/t/p/w45/aO5ILS7qnqtFIprbJ40zla0jhpu.jpg", "Jesse Freeman is a former special forces officer and explosives expert now working a regular job as a security guard in a state-of-the-art basketball arena. Trouble erupts when a tech-savvy cadre of terrorists kidnap the team's owner and Jesse's daughter during opening night. Facing a ticking clock and impossible odds, it's up to Jesse to not only save them but also a full house of fans in this highly charged action thriller.", "Welcome to Sudden Death", 6.4f, false, null, "en", "Welcome to Sudden Death", null, false, 137)));
        movieList.add(new MovieCartItem(new Movie("438396", "http://image.tmdb.org/t/p/w92/vJHSParlylICnI7DuuI54nfTPRR.jpg", "http://image.tmdb.org/t/p/w45/qGZe9qTuydxyJYQ60XDtEckzLR8.jpg", "In Madrid, Spain, a mysterious serial killer ruthlessly murders his victims by recreating the first appearance of several comic book superheroes. Cosme, a veteran police inspector who is about to retire, works on the case along with the tormented inspector David Valentín and his own son Jorge Elías, a nerdy young man who owns a comic book store.", "Unknown Origins", 6.2f, false, null, "es", "Orígenes secretos", null, false, 225)));
        movieList.add(new MovieCartItem(new Movie("741074", "http://image.tmdb.org/t/p/w92/zfdhsR3Y3xw42OHrMpi0oBw0Uk8.jpg", "http://image.tmdb.org/t/p/w45/DA7gzvlBoxMNL0XmGgTZOyv67P.jpg", "The previously untold origins of Olaf, the innocent and insightful, summer-loving snowman are revealed as we follow Olaf’s first steps as he comes to life and searches for his identity in the snowy mountains outside Arendelle.", "Once Upon a Snowman", 7.7f, false, null, "en", "Once Upon a Snowman", null, false, 86)));
        movieList.add(new MovieCartItem(new Movie("697064", "http://image.tmdb.org/t/p/w92/z0r3YjyJSLqf6Hz0rbBAnEhNXQ7.jpg", "http://image.tmdb.org/t/p/w45/7WKIOXJa2JjHygE8Yta3uaCv6GC.jpg", "A contract killer, becomes the reverend of a LA church, until a cult leader and his minions kidnap his daughter. Blinded by vengeance, he cuts a bloody path across the city. The only thing that can stop him is his newfound faith.", "Beckman", 5.5f, false, null, "en", "Beckman", null, false, 23)));
        movieList.add(new MovieCartItem(new Movie("528085", "http://image.tmdb.org/t/p/w92/7D430eqZj8y3oVkLFfsWXGRcpEG.jpg", "http://image.tmdb.org/t/p/w45/5UkzNSOK561c2QRy2Zr4AkADzLT.jpg", "A lowly utility worker is called to the future by a mysterious radio signal, he must leave his dying wife to embark on a journey that will force him to face his deepest fears in an attempt to change the fabric of reality and save humankind from its greatest environmental crisis yet.", "2067", 5.1f, false, null, "en", "2067", null, false, 240)));
        movieList.add(new MovieCartItem(new Movie("560050", "http://image.tmdb.org/t/p/w92/lQfdytwN7eh0tXWjIiMceFdBBvD.jpg", "http://image.tmdb.org/t/p/w45/htBUhLSS7FfHtydgYxUWjL3J1Q1.jpg", "A girl builds a rocket to travel to the moon in hopes of meeting the legendary Moon Goddess.", "Over the Moon", 7.6f, false, null, "en", "Over the Moon", null, false, 251)));
        movieList.add(new MovieCartItem(new Movie("499338", "http://image.tmdb.org/t/p/w92/j8D3jXHtA9cNb4epzvmA6hymKQ4.jpg", "http://image.tmdb.org/t/p/w45/fUxq6ilPW01roOpqB5g9SOS3zZv.jpg", "A 9 year old boy experiences God's power in a supernatural way.", "I Believe", 3.8f, false, null, "en", "I Believe", null, false, 4)));
    }

}
